import fs from 'fs';
import path from 'path';
import os from 'os';
import dotenv from 'dotenv';

/**
 * Ensures a .env file exists and loads it.
 * This runs at application bootstrap.
 */
export function initializeEnv() {
  const envPath = path.resolve(process.cwd(), '../.env');

  // Check if .env exists
  if (!fs.existsSync(envPath)) {
    console.warn(`⚠️ .env file not found at ${envPath}. Creating default...`);
    const home = os.homedir();
    const defaultEnv = `
# Default configuration generated by MessageHub

WORKSPACE_PATH="${path.resolve(process.cwd(), '../data')}"
ROOT_IMPORT_PATH="${home}"
ROOT_WORKSPACE_PATH="${home}"
`;
    // We navigate up one level from webapp root to match project structure
    fs.writeFileSync(envPath, defaultEnv.trim());
    console.info(`✅ Created .env file: ${defaultEnv}`);
  }

  // Load/Reload environment variables
  const result = dotenv.config({ path: envPath });

  if (result.error) {
    console.error('❌  Failed to load .env file:', result.error);
  } else {
    console.info('✅  Environment variables loaded from .env');
  }
}

// Auto-run on import to ensure environments are set before other modules access them
initializeEnv();
