
import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const platform = searchParams.get('platform');

  if (platform !== 'FB') {
    // Only FB supported for now
    return NextResponse.json([]);
  }

  // Path to the index file generated by python script
  // We are in /web-ui/src/app/api/threads. 
  // Root is /web-ui.
  // Data is in ../data/FB/fb_threads_index.json
  const indexPath = path.join(process.cwd(), '../data/FB/fb_threads_index.json');

  try {
    const fileContents = fs.readFileSync(indexPath, 'utf8');
    const data = JSON.parse(fileContents);
    return NextResponse.json(data);
  } catch (error) {
    console.error("Error reading index:", error);
    return NextResponse.json({ error: 'Failed to load threads' }, { status: 500 });
  }
}
